### ISSUE TITLE
Warnings during grunt build

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#1225]
### Non-existent property access inside circular dep:

```
(node:16261) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16261) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:16261) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
```

### Unsupported TS

(Is this me?)

```
Warning: You are running with an unsupported TypeScript version! TypeDoc supports 4.0, 4.1, 4.2, 4.3, 4.4
```

**Comment by ronyeh** [comment]
I looked into this last week, and it's possible that one of our node modules uses `shelljs` which causes these warnings. You can try searching for the error messages. Maybe we can manually bump shelljs to see if it goes away.

The TS issue is from me. :-) I upgraded us to TS 4.5 RC. Once TS 4.5 is officially released, TypeDoc will catch up and then that warning will go away.

**Comment by ronyeh** [comment]
It does look like it is shelljs. We don't require it directly, but one of our dependencies does. Not sure how to upgrade shelljs by itself, if our dependencies require a specific (older) version of it. 

```bash
$ node --trace-warnings /usr/local/bin/grunt


(node:32728) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/cd.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/chmod.js:32:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/cp.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/dirs.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/dirs.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/dirs.js:11:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/echo.js:3:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/tempdir.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/pwd.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/exec.js:10:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/ls.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/find.js:6:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/grep.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/head.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/ln.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/mkdir.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/rm.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/mv.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/sed.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/set.js:3:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/sort.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/tail.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/test.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/to.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/toEnd.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/touch.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/uniq.js:13:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
(node:32728) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object._register [as register] (vexflow/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (vexflow/node_modules/shelljs/src/which.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

```

**Comment by ronyeh** [comment]
```bash 
$> npm ls shelljs
vexflow@4.0.0 
├─┬ grunt-release@0.14.0
│ └── shelljs@0.7.8
└─┬ grunt-typedoc@0.2.4
  └─┬ typedoc@0.4.5
    └── shelljs@0.7.8 deduped
```
Current shelljs is 0.8.4, so maybe we can upgrade those two dependencies.

**Comment by 0xfe** [comment]
Good find. Is there an alternative to `grunt-release`?

**Comment by ronyeh** [comment]
I'd vote for putting together an interactive step-by-step node script that does the same thing. (Yeah, we'd be reinventing the wheel a little.)

It would use built in node / npm / git / github CLI commands. For example, bumping the version number is: `npm version` 
https://docs.npmjs.com/cli/v6/commands/npm-version

It could also log the exact commands it will run, and the user can hit enter to confirm each one, or ctrl-c to abort.

This method would be more explicit (less "magic") than grunt-release, and since it's just a node script, it can be run without grunt. For example: `npm run releaseTheNewVersion` or `node ./tools/releaseNow.js`
