### ISSUE TITLE
Build failures when building with sourcemap

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1289]
Did a fresh clone and npm install.  Ran `set VEX_DEVTOOL='true';grunt webpack:buildDebugPlusTests`

As an aside, I don't understand why you would want a debug  build and no source map - is it possible to do source-level debugging without it? 

The change notes seemed to suggest that you would get a full source map when doing a production build.  I tried 'webpack:productionAllFonts' but there was no source map generated with this option.

I loved the buildDebugPlusTestTarget that we had, for a second, it did a debug build really fast and made development much easier.

```
C:\Users\Daddy\Documents\GitHub\vf2\vexflow>grunt webpack:buildDebugPlusTests
Running "webpack:buildDebugPlusTests" (webpack) task
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.
    at validate (C:\Users\Daddy\Documents\GitHub\vf2\vexflow\node_modules\schema-utils\dist\validate.js:105:11)
    at validateSchema (C:\Users\Daddy\Documents\GitHub\vf2\vexflow\node_modules\webpack\lib\validateSchema.js:78:2)
    at create (C:\Users\Daddy\Documents\GitHub\vf2\vexflow\node_modules\webpack\lib\webpack.js:111:24)
    at webpack (C:\Users\Daddy\Documents\GitHub\vf2\vexflow\node_modules\webpack\lib\webpack.js:158:32)
    at f (C:\Users\Daddy\Documents\GitHub\vf2\vexflow\node_modules\webpack\lib\index.js:58:16)
    at C:\Users\Daddy\Documents\GitHub\vf2\vexflow\node_modules\grunt-webpack\tasks\webpack.js:60:28
    at C:\Users\Daddy\Documents\GitHub\vf2\vexflow\node_modules\grunt-webpack\src\options\OptionHelper.js:18:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      keyword: 'anyOf',
      dataPath: '.devtool',
      schemaPath: '#/definitions/DevTool/anyOf',
      params: {},
      message: 'should match some schema in anyOf',
      schema: [Array],
      parentSchema: [Object],
      data: "'true'",
      children: [Array]
    }
  ],
  schema: {
    definitions: {
      Amd: [Object],
      AssetFilterItemTypes: [Object],
      AssetFilterTypes: [Object],
      AssetGeneratorDataUrl: [Object],
      AssetGeneratorDataUrlFunction: [Object],
      AssetGeneratorDataUrlOptions: [Object],
      AssetGeneratorOptions: [Object],
      AssetInlineGeneratorOptions: [Object],
      AssetModuleFilename: [Object],
      AssetParserDataUrlFunction: [Object],
      AssetParserDataUrlOptions: [Object],
      AssetParserOptions: [Object],
      AssetResourceGeneratorOptions: [Object],
      AuxiliaryComment: [Object],
      Bail: [Object],
      CacheOptions: [Object],
      CacheOptionsNormalized: [Object],
      Charset: [Object],
      ChunkFilename: [Object],
      ChunkFormat: [Object],
      ChunkLoadTimeout: [Object],
      ChunkLoading: [Object],
      ChunkLoadingGlobal: [Object],
      ChunkLoadingType: [Object],
      Clean: [Object],
      CleanOptions: [Object],
      CompareBeforeEmit: [Object],
      Context: [Object],
      CrossOriginLoading: [Object],
      Dependencies: [Object],
      DevServer: [Object],
      DevTool: [Object],
      DevtoolFallbackModuleFilenameTemplate: [Object],
      DevtoolModuleFilenameTemplate: [Object],
      DevtoolNamespace: [Object],
      EmptyGeneratorOptions: [Object],
      EmptyParserOptions: [Object],
      EnabledChunkLoadingTypes: [Object],
      EnabledLibraryTypes: [Object],
      EnabledWasmLoadingTypes: [Object],
      Entry: [Object],
      EntryDescription: [Object],
      EntryDescriptionNormalized: [Object],
      EntryDynamic: [Object],
      EntryDynamicNormalized: [Object],
      EntryFilename: [Object],
      EntryItem: [Object],
      EntryNormalized: [Object],
      EntryObject: [Object],
      EntryRuntime: [Object],
      EntryStatic: [Object],
      EntryStaticNormalized: [Object],
      EntryUnnamed: [Object],
      Environment: [Object],
      Experiments: [Object],
      ExperimentsCommon: [Object],
      ExperimentsNormalized: [Object],
      ExternalItem: [Object],
      ExternalItemFunctionData: [Object],
      ExternalItemValue: [Object],
      Externals: [Object],
      ExternalsPresets: [Object],
      ExternalsType: [Object],
      FileCacheOptions: [Object],
      Filename: [Object],
      FilenameTemplate: [Object],
      FilterItemTypes: [Object],
      FilterTypes: [Object],
      GeneratorOptionsByModuleType: [Object],
      GlobalObject: [Object],
      HashDigest: [Object],
      HashDigestLength: [Object],
      HashFunction: [Object],
      HashSalt: [Object],
      HotUpdateChunkFilename: [Object],
      HotUpdateGlobal: [Object],
      HotUpdateMainFilename: [Object],
      HttpUriAllowedUris: [Object],
      HttpUriOptions: [Object],
      HttpUriOptionsAllowedUris: [Object],
      IgnoreWarnings: [Object],
      IgnoreWarningsNormalized: [Object],
      Iife: [Object],
      ImportFunctionName: [Object],
      ImportMetaName: [Object],
      InfrastructureLogging: [Object],
      JavascriptParserOptions: [Object],
      Layer: [Object],
      LazyCompilationDefaultBackendOptions: [Object],
      LazyCompilationOptions: [Object],
      Library: [Object],
      LibraryCustomUmdCommentObject: [Object],
      LibraryCustomUmdObject: [Object],
      LibraryExport: [Object],
      LibraryName: [Object],
      LibraryOptions: [Object],
      LibraryType: [Object],
      Loader: [Object],
      MemoryCacheOptions: [Object],
      Mode: [Object],
      ModuleFilterItemTypes: [Object],
      ModuleFilterTypes: [Object],
      ModuleOptions: [Object],
      ModuleOptionsNormalized: [Object],
      Name: [Object],
      NoParse: [Object],
      Node: [Object],
      NodeOptions: [Object],
      Optimization: [Object],
      OptimizationRuntimeChunk: [Object],
      OptimizationRuntimeChunkNormalized: [Object],
      OptimizationSplitChunksCacheGroup: [Object],
      OptimizationSplitChunksGetCacheGroups: [Object],
      OptimizationSplitChunksOptions: [Object],
      OptimizationSplitChunksSizes: [Object],
      Output: [Object],
      OutputModule: [Object],
      OutputNormalized: [Object],
      Parallelism: [Object],
      ParserOptionsByModuleType: [Object],
      Path: [Object],
      Pathinfo: [Object],
      Performance: [Object],
      PerformanceOptions: [Object],
      Plugins: [Object],
      Profile: [Object],
      PublicPath: [Object],
      RawPublicPath: [Object],
      RecordsInputPath: [Object],
      RecordsOutputPath: [Object],
      RecordsPath: [Object],
      Resolve: [Object],
      ResolveAlias: [Object],
      ResolveLoader: [Object],
      ResolveOptions: [Object],
      ResolvePluginInstance: [Object],
      RuleSetCondition: [Object],
      RuleSetConditionAbsolute: [Object],
      RuleSetConditionOrConditions: [Object],
      RuleSetConditionOrConditionsAbsolute: [Object],
      RuleSetConditions: [Object],
      RuleSetConditionsAbsolute: [Object],
      RuleSetLoader: [Object],
      RuleSetLoaderOptions: [Object],
      RuleSetLogicalConditions: [Object],
      RuleSetLogicalConditionsAbsolute: [Object],
      RuleSetRule: [Object],
      RuleSetRules: [Object],
      RuleSetUse: [Object],
      RuleSetUseItem: [Object],
      ScriptType: [Object],
      SnapshotOptions: [Object],
      SourceMapFilename: [Object],
      SourcePrefix: [Object],
      StatsOptions: [Object],
      StatsValue: [Object],
      StrictModuleErrorHandling: [Object],
      StrictModuleExceptionHandling: [Object],
      Target: [Object],
      TrustedTypes: [Object],
      UmdNamedDefine: [Object],
      UniqueName: [Object],
      WarningFilterItemTypes: [Object],
      WarningFilterTypes: [Object],
      WasmLoading: [Object],
      WasmLoadingType: [Object],
      Watch: [Object],
      WatchOptions: [Object],
      WebassemblyModuleFilename: [Object],
      WebpackOptionsNormalized: [Object],
      WebpackPluginFunction: [Object],
      WebpackPluginInstance: [Object]
    },
    title: 'WebpackOptions',
    description: 'Options object as provided by the user.',
    type: 'object',
    additionalProperties: false,
    properties: {
      amd: [Object],
      bail: [Object],
      cache: [Object],
      context: [Object],
      dependencies: [Object],
      devServer: [Object],
      devtool: [Object],
      entry: [Object],
      experiments: [Object],
      externals: [Object],
      externalsPresets: [Object],
      externalsType: [Object],
      ignoreWarnings: [Object],
      infrastructureLogging: [Object],
      loader: [Object],
      mode: [Object],
      module: [Object],
      name: [Object],
      node: [Object],
      optimization: [Object],
      output: [Object],
      parallelism: [Object],
      performance: [Object],
      plugins: [Object],
      profile: [Object],
      recordsInputPath: [Object],
      recordsOutputPath: [Object],
      recordsPath: [Object],
      resolve: [Object],
      resolveLoader: [Object],
      snapshot: [Object],
      stats: [Object],
      target: [Object],
      watch: [Object],
      watchOptions: [Object]
    }
  },
  headerName: 'Webpack',
  baseDataPath: 'configuration',
  postFormatter: [Function: postFormatter]
}
Fatal error: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
   BREAKING CHANGE since webpack 5: The devtool option is more strict.
   Please strictly follow the order of the keywords in the pattern.
```

**Comment by AaronDavidNewman** [comment]
I think this is just a merge issue.  I was able to fix it this way:

```
const devtool = (process.env.VEX_DEVTOOL || mode === DEVELOPMENT_MODE) ? 'source-map' : false;
```

This will restore it doing what it used to do.  However, if you want it to do what the comment says:

> If not specified, production builds will get high quality source maps, and development/debug builds will get nothing.

Then it should be:
```
const devtool = (process.env.VEX_DEVTOOL || mode === PRODUCTION_MODE) ? 'source-map' : false;
```
I guess the comment is the correct behavior?  In which case I will submit that.

**Comment by 0xfe** [comment]
@ronyeh is looking at grunt right now, and can suggest.

My preference is the first option (make it do what it used to do), which is the least disruptive to others. (This logic is changing anyway in Ron's gruntfile PR.)

**Comment by AaronDavidNewman** [comment]
Actually I said something above that wasn't correct.

This is how it worked in 3.0.9.:
```
const devtool = (process.env.VEX_DEVTOOL || mode === PRODUCTION_MODE) ? 'source-map' : false
```


This is how it worked in 4.0, prior to the this week:
```
const devtool = (process.env.VEX_DEVTOOL || mode === DEVELOPMENT_MODE) ? 'source-map' : false;
```

I'm good with either thing, I defer to the will of the group. Right now, though, neither thing works and you can't get a source map at all.

**Comment by mscuthbert** [comment]
My logic is that if someone is using (but not developing) Vexflow, and a problem arises, a SourceMap will allow them to figure out what went wrong -- what the proper types should be, whether any dev notes talk about the error, etc.  Without the source map, they will be left in the dark or have to compile their own.  It won't raise the size of their bundle, just their own sourcemap bundle.

**Comment by AaronDavidNewman** [comment]
It worked for me.  Thanks...

**Comment by rvilarl** [comment]
It also worked for me
