### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by philipp-siegmantel** [0xfe/vexflow#809]
I'm trying to test a TypeScript React component that uses Vexflow with Jest, but apparently Jest is unable import VexFlow. I get the following error.
```
    /Users/di39cuw/Documents/nebenjob/sspfe/frontend/node_modules/vexflow/src/index.js:3
    import { Vex } from './vex';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React, { CSSProperties } from "react";
      2 | import { Key, Note } from "../Note";
    > 3 | const Vex = require("vexflow");
        |             ^
      4 | 
      5 | const Flow = Vex.Flow;
      6 | 

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/NoteBar.tsx:3:13)
```
I also tried the `import` variant with the same results.

**Comment by philipp-siegmantel** [comment]
I solved it by adding the following to my package.json.
```
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(vexflow)/)"
    ]
  },
```
